DELETE FROM USERCONFIGURATION WHERE CONFIG_KEY = 'spielerUebersichtsPanel_horizontalRightSplitPane';
DELETE FROM USERCONFIGURATION WHERE CONFIG_KEY = 'aufstellungsPanel_verticalSplitPane';
DELETE FROM USERCONFIGURATION WHERE CONFIG_KEY = 'aufstellungsPanel_horizontalRightSplitPane';
DELETE FROM USERCONFIGURATION WHERE CONFIG_KEY = 'aufstellungsPanel_horizontalLeftSplitPane';

ALTER TABLE BASICS ADD COLUMN SeasonOffset INTEGER;

ALTER TABLE MATCHESKURZINFO ADD COLUMN Duration INTEGER;


ALTER TABLE MATCHHIGHLIGHTS ADD COLUMN MatchPart INTEGER;
ALTER TABLE MATCHHIGHLIGHTS ADD COLUMN EventVariation INTEGER;


ALTER TABLE MATCHDETAILS ADD COLUMN HomeGoal0 INTEGER;
ALTER TABLE MATCHDETAILS ADD COLUMN HomeGoal1 INTEGER;
ALTER TABLE MATCHDETAILS ADD COLUMN HomeGoal2 INTEGER;
ALTER TABLE MATCHDETAILS ADD COLUMN HomeGoal3 INTEGER;
ALTER TABLE MATCHDETAILS ADD COLUMN HomeGoal4 INTEGER;
ALTER TABLE MATCHDETAILS ADD COLUMN GuestGoal0 INTEGER;
ALTER TABLE MATCHDETAILS ADD COLUMN GuestGoal1 INTEGER;
ALTER TABLE MATCHDETAILS ADD COLUMN GuestGoal2 INTEGER;
ALTER TABLE MATCHDETAILS ADD COLUMN GuestGoal3 INTEGER;
ALTER TABLE MATCHDETAILS ADD COLUMN GuestGoal4 INTEGER;


ALTER TABLE TA_PLAYER ADD COLUMN NAME VARCHAR (100);

DROP TABLE FAKTOREN;
CREATE TABLE FAKTOREN(
    POSITIONID INTEGER NOT NULL PRIMARY KEY,
    GKFACTOR DOUBLE NOT NULL,
    DEFACTOR DOUBLE NOT NULL,
    WIFACTOR DOUBLE NOT NULL,
    PSFACTOR DOUBLE NOT NULL,
    SPFACTOR DOUBLE NOT NULL,
    SCFACTOR DOUBLE NOT NULL,
    PMFACTOR DOUBLE NOT NULL,
    NORMALISATIONFACTOR DOUBLE NOT NULL
);


-- Reset user columns.
DELETE FROM USERCOLUMNS WHERE COLUMN_ID BETWEEN 2000 AND 3000;
DELETE FROM USERCOLUMNS WHERE COLUMN_ID BETWEEN 3000 AND 4000


CREATE TABLE FUTUREPLAYERTRAINING(
       playerId INTEGER NOT NULL,
       fromWeek INTEGER NOT NULL,
       fromSeason INTEGER NOT NULL,
       toWeek INTEGER,
       toSeason INTEGER,
       prio INTEGER
);
