
-- Translate FINANZEN table and columns to English.
ALTER TABLE FINANZEN ALTER COLUMN Datum RENAME TO FetchedDate;
ALTER TABLE FINANZEN ALTER COLUMN Supporter RENAME TO SupportersPopularity;
ALTER TABLE FINANZEN ALTER COLUMN Sponsoren RENAME TO SponsorsPopularity;
ALTER TABLE FINANZEN ALTER COLUMN Finanzen RENAME TO Cash;
ALTER TABLE FINANZEN ALTER COLUMN EinSponsoren RENAME TO IncomeSponsors;
ALTER TABLE FINANZEN ALTER COLUMN EinZuschauer RENAME TO IncomeSpectators;
ALTER TABLE FINANZEN ALTER COLUMN EinZinsen RENAME TO IncomeFinancial;
ALTER TABLE FINANZEN ALTER COLUMN EinSonstiges RENAME TO IncomeTemporary;
ALTER TABLE FINANZEN ALTER COLUMN EinGesamt RENAME TO IncomeSum;
ALTER TABLE FINANZEN ALTER COLUMN KostSpieler RENAME TO CostsPlayers;
ALTER TABLE FINANZEN ALTER COLUMN KostTrainer RENAME TO CostsStaff;
ALTER TABLE FINANZEN ALTER COLUMN KostStadion RENAME TO CostsArena;
ALTER TABLE FINANZEN ALTER COLUMN KostJugend RENAME TO CostsYouth;
ALTER TABLE FINANZEN ALTER COLUMN KostZinsen RENAME TO CostsFinancial;
ALTER TABLE FINANZEN ALTER COLUMN KostSonstiges RENAME TO CostsTemporary;
ALTER TABLE FINANZEN ALTER COLUMN KostGesamt RENAME TO CostsSum;
ALTER TABLE FINANZEN ALTER COLUMN GewinnVerlust RENAME TO ExpectedWeeksTotal;
ALTER TABLE FINANZEN ALTER COLUMN LetzteEinSponsoren RENAME TO LastIncomeSponsors;
ALTER TABLE FINANZEN ALTER COLUMN LetzteEinZuschauer RENAME TO LastIncomeSpectators;
ALTER TABLE FINANZEN ALTER COLUMN LetzteEinZinsen RENAME TO LastIncomeFinancial;
ALTER TABLE FINANZEN ALTER COLUMN LetzteEinSonstiges RENAME TO LastIncomeTemporary;
ALTER TABLE FINANZEN ALTER COLUMN LetzteEinGesamt RENAME TO LastIncomeSum;
ALTER TABLE FINANZEN ALTER COLUMN LetzteKostSpieler RENAME TO LastCostsPlayers;
ALTER TABLE FINANZEN ALTER COLUMN LetzteKostTrainer RENAME TO LastCostsStaff;
ALTER TABLE FINANZEN ALTER COLUMN LetzteKostStadion RENAME TO LastCostsArena;
ALTER TABLE FINANZEN ALTER COLUMN LetzteKostJugend RENAME TO LastCostsYouth;
ALTER TABLE FINANZEN ALTER COLUMN LetzteKostZinsen RENAME TO LastCostsFinancial;
ALTER TABLE FINANZEN ALTER COLUMN LetzteKostSonstiges RENAME TO LastCostsTemporary;
ALTER TABLE FINANZEN ALTER COLUMN LetzteKostGesamt RENAME TO LastCostsSum;
ALTER TABLE FINANZEN ALTER COLUMN LetzteGewinnVerlust RENAME TO LastWeeksTotal;
ALTER TABLE FINANZEN ADD COLUMN ExpectedCash INTEGER DEFAULT 0;
ALTER TABLE FINANZEN ADD COLUMN IncomeSoldPlayers INTEGER DEFAULT 0;
ALTER TABLE FINANZEN ADD COLUMN IncomeSoldPlayersCommission INTEGER DEFAULT 0;
ALTER TABLE FINANZEN ADD COLUMN CostsBoughtPlayers INTEGER DEFAULT 0;
ALTER TABLE FINANZEN ADD COLUMN CostsArenaBuilding INTEGER DEFAULT 0;
ALTER TABLE FINANZEN ADD COLUMN LastIncomeSoldPlayers INTEGER DEFAULT 0;
ALTER TABLE FINANZEN ADD COLUMN LastIncomeSoldPlayersCommission INTEGER DEFAULT 0;
ALTER TABLE FINANZEN ADD COLUMN LastCostsBoughtPlayers INTEGER DEFAULT 0;
ALTER TABLE FINANZEN ADD COLUMN LastCostsArenaBuilding INTEGER DEFAULT 0;
ALTER TABLE FINANZEN RENAME TO ECONOMY;



ALTER TABLE MATCHDETAILS ADD COLUMN HomeFormation VARCHAR(5);
ALTER TABLE MATCHDETAILS ADD COLUMN AwayFormation VARCHAR(5);
ALTER TABLE MATCHDETAILS ADD COLUMN SourceSystem INTEGER DEFAULT 0 Not Null;


ALTER TABLE BASICS ADD COLUMN YouthTeamName VARCHAR(127);
ALTER TABLE BASICS ADD COLUMN YouthTeamID INTEGER;


ALTER TABLE AUFSTELLUNG ADD COLUMN SourceSystem INTEGER DEFAULT 0 Not Null;


ALTER TABLE MATCHLINEUPPLAYER ADD COLUMN StartSetPieces BOOLEAN;
ALTER TABLE MATCHLINEUPPLAYER ADD COLUMN SourceSystem INTEGER DEFAULT 0 Not Null;


ALTER TABLE MATCHLINEUP ADD COLUMN SourceSystem INTEGER DEFAULT 0 Not Null;


ALTER TABLE MATCHLINEUPTEAM ADD COLUMN SourceSystem INTEGER DEFAULT 0 Not Null;


ALTER TABLE MATCHSUBSTITUTION ADD COLUMN SourceSystem INTEGER DEFAULT 0 Not Null;


ALTER TABLE MATCHHIGHLIGHTS ADD COLUMN MatchDate TIMESTAMP;
ALTER TABLE MATCHHIGHLIGHTS ADD COLUMN SourceSystem INTEGER DEFAULT 0 Not Null;


-- Youth Team support
CREATE TABLE YOUTHTRAINING(
       MATCHID INTEGER NOT NULL,
       TRAINING1 INTEGER,
       TRAINING2 INTEGER
);


CREATE TABLE YOUTHPLAYER(
       HRF_ID INTEGER NOT NULL,
       ID INTEGER NOT NULL,
       FIRSTNAME VARCHAR(100),
       NICKNAME VARCHAR(100),
       LASTNAME VARCHAR(100),
       AGE INTEGER NOT NULL,
       AGEDAYS INTEGER NOT NULL,
       ARRIVALDATE TIMESTAMP,
       PROMOTIONDATE TIMESTAMP,
       CANBEPROMOTEDIN INTEGER NOT NULL,
       PLAYERNUMBER VARCHAR(10),
       STATEMENT VARCHAR(255),
       OWNERNOTES VARCHAR(255),
       PLAYERCATEGORYID INTEGER NOT NULL,
       CARDS INTEGER NOT NULL,
       INJURYLEVEL INTEGER,
       SPECIALTY INTEGER,
       CAREERGOALS INTEGER,
       CAREERHATTRICKS INTEGER,
       LEAGUEGOALS INTEGER,
       FRIENDLYGOALS INTEGER,
       SCOUTID INTEGER,
       SCOUTINGREGIONID INTEGER,
       SCOUTNAME VARCHAR(255),
       YOUTHMATCHID INTEGER,
       POSITIONCODE INTEGER,
       PLAYEDMINUTES INTEGER,
       RATING INTEGER,
       YOUTHMATCHDATE TIMESTAMP,
       KEEPER INTEGER,
       KEEPERMAX INTEGER,
       KEEPERSTART INTEGER,
       KEEPERISMAXREACHED BOOLEAN NOT NULL,
       KEEPERVALUE DOUBLE NOT NULL,
       KEEPERSTARTVALUE DOUBLE NOT NULL,
       KEEPERTOP3 BOOLEAN,
       DEFENDER INTEGER,
       DEFENDERMAX INTEGER,
       DEFENDERSTART INTEGER,
       DEFENDERISMAXREACHED BOOLEAN NOT NULL,
       DEFENDERVALUE DOUBLE NOT NULL,
       DEFENDERSTARTVALUE DOUBLE NOT NULL,
       DEFENDERTOP3 BOOLEAN,
       PLAYMAKER INTEGER,
       PLAYMAKERMAX INTEGER,
       PLAYMAKERSTART INTEGER,
       PLAYMAKERISMAXREACHED BOOLEAN NOT NULL,
       PLAYMAKERVALUE DOUBLE NOT NULL,
       PLAYMAKERSTARTVALUE DOUBLE NOT NULL,
       PLAYMAKERTOP3 BOOLEAN,
       WINGER INTEGER,
       WINGERMAX INTEGER,
       WINGERSTART INTEGER,
       WINGERISMAXREACHED BOOLEAN NOT NULL,
       WINGERVALUE DOUBLE NOT NULL,
       WINGERSTARTVALUE DOUBLE NOT NULL,
       WINGERTOP3 BOOLEAN,
       PASSING INTEGER,
       PASSINGMAX INTEGER,
       PASSINGSTART INTEGER,
       PASSINGISMAXREACHED BOOLEAN NOT NULL,
       PASSINGVALUE DOUBLE NOT NULL,
       PASSINGSTARTVALUE DOUBLE NOT NULL,
       PASSINGTOP3 BOOLEAN,
       SCORER INTEGER,
       SCORERMAX INTEGER,
       SCORERSTART INTEGER,
       SCORERISMAXREACHED BOOLEAN NOT NULL,
       SCORERVALUE DOUBLE NOT NULL,
       SCORERSTARTVALUE DOUBLE NOT NULL,
       SCORERTOP3 BOOLEAN,
       SETPIECES INTEGER,
       SETPIECESMAX INTEGER,
       SETPIECESSTART INTEGER,
       SETPIECESISMAXREACHED BOOLEAN NOT NULL,
       SETPIECESVALUE DOUBLE NOT NULL,
       SETPIECESSTARTVALUE DOUBLE NOT NULL,
       SETPIECESTOP3 BOOLEAN
);

CREATE TABLE YOUTHSCOUTCOMMENT(
       YOUTHPLAYER_ID INTEGER NOT NULL,
       INDEX INTEGER NOT NULL,
       TEXT VARCHAR(255),
       TYPE INTEGER,
       VARIATION INTEGER,
       SKILLTYPE INTEGER,
       SKILLLEVEL INTEGER
);

CREATE TABLE CLUBS_LOGO(
       TEAM_ID INTEGER NOT NULL PRIMARY KEY,
       URL VARCHAR(256),
       FILENAME VARCHAR(256),
       LAST_ACCESS TIMESTAMP
);


ALTER TABLE TRAINING ADD COLUMN COACH_LEVEL INTEGER;
ALTER TABLE TRAINING ADD COLUMN TRAINING_ASSISTANTS_LEVEL INTEGER;
ALTER TABLE TRAINING ADD COLUMN SOURCE INTEGER;
ALTER TABLE TRAINING ADD COLUMN TRAINING_DATE TIMESTAMP;


-- TODO Get data from other tables


ALTER TABLE TRAINING ALTER COLUMN COACH_LEVEL SET NOT NULL;
ALTER TABLE TRAINING ALTER COLUMN TRAINING_ASSISTANTS_LEVEL SET NOT NULL;
ALTER TABLE TRAINING ALTER COLUMN TRAINING_DATE SET NOT NULL;
ALTER TABLE TRAINING ALTER COLUMN SOURCE SET NOT NULL;
ALTER TABLE TRAINING ALTER COLUMN TYP RENAME TO TRAINING_TYPE;
ALTER TABLE TRAINING ALTER COLUMN INTENSITY RENAME TO TRAINING_INTENSITY;
ALTER TABLE TRAINING ALTER COLUMN STAMINATRAININGPART RENAME TO STAMINA_SHARE;
ALTER TABLE TRAINING DROP COLUMN YEAR;
ALTER TABLE TRAINING DROP COLUMN WEEK;


ALTER TABLE FUTURETRAINING ADD COLUMN COACH_LEVEL INTEGER;
ALTER TABLE FUTURETRAINING ADD COLUMN TRAINING_ASSISTANTS_LEVEL INTEGER;
ALTER TABLE FUTURETRAINING ADD COLUMN SOURCE INTEGER;
ALTER TABLE FUTURETRAINING ADD COLUMN TRAINING_DATE TIMESTAMP;

UPDATE
       FUTURETRAINING
SET
       TRAINING_DATE = timestamp('1900-01-01'),
       TRAINING_ASSISTANTS_LEVEL = WEEK,
       COACH_LEVEL = SEASON,
       SOURCE = 'MANUAL';

ALTER TABLE FUTURETRAINING ALTER COLUMN COACH_LEVEL SET NOT NULL;
ALTER TABLE FUTURETRAINING ALTER COLUMN TRAINING_ASSISTANTS_LEVEL SET NOT NULL;
ALTER TABLE FUTURETRAINING ALTER COLUMN TRAINING_DATE SET NOT NULL;
ALTER TABLE FUTURETRAINING ALTER COLUMN SOURCE SET NOT NULL;
ALTER TABLE FUTURETRAINING ALTER COLUMN TYPE RENAME TO TRAINING_TYPE;
ALTER TABLE FUTURETRAINING ALTER COLUMN INTENSITY RENAME TO TRAINING_INTENSITY;
ALTER TABLE FUTURETRAINING ALTER COLUMN STAMINATRAININGPART RENAME TO STAMINA_SHARE;
ALTER TABLE FUTURETRAINING DROP COLUMN SEASON;
ALTER TABLE FUTURETRAINING DROP COLUMN WEEK;
